version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3030:3030"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/myDatabase # Verbindung zu Mongo im Docker-Netzwerk
      - JWT_SECRET=your-secret-key                # Falls dein Backend JWT verwendet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:

